### ISSUE TITLE
How to control computer through Alexa.

### ISSUE THREAD

**Issue by phpmind** [miguelmota/alexa-voice-service.js#6]
How to control computer through Alexa.
* open websites
* open applications
* pause/play media (if it's in focus)
* control volume (up, down, mute)
* run a text search (again, in whatever program is in focus)
* lock the computer. 

Thanks miguel. 
I am your fan :)

**Comment by miguelmota** [comment]
Sounds like you might need a general purpose speech recognizer, such as [pocketsphinx](https://github.com/cmusphinx/pocketsphinx), to get you started on command and control type of applications. The tasks mentioned seem to be out of Alexa's scope. You'll have better luck asking in the [Alexa Forums](https://forums.developer.amazon.com/spaces/165/index.html). Closing this out since it is out of scope for this library. Thanks!
