### ISSUE TITLE
Problem with Amazon auth 

### ISSUE THREAD

**Issue by waigel** [miguelmota/alexa-voice-service.js#9]
I have an Problem, I installed your git reposetory succesfuel.
And the Website are [online](https://server1.verifybot.de:9745/). But the error Comes on push the Login butten: 

`The redirect URI you provided has not been whitelisted for your application. Please add your redirect URI in the 'Allowed Return URLs' section under 'Web Settings' for your Security Profile on Amazon Developer Portal.
Request Details
client_id=amzn1.application-oa2-client.696ab90fc5844fdbb8efc17394a79c00
scope=alexa%3Aall
scope_data=%7B%22alexa%3Aall%22%3A%7B%22productID%22%3A%22test_device%22%2C%22productInstanceAttributes%22%3A%7B%22deviceSerialNumber%22%3A123%7D%7D%7D
response_type=token
redirect_uri=https://server1.verifybot.de:9745/authresponse
`

But i have set the right Redirect URL.  Show the pictue. https://i.gyazo.com/dfca95094b9c3c4c8e0cb3df0293dcd4.png

Pleas help me.

**Comment by miguelmota** [comment]
Hi @VerHext,

I see that your didn't update the `clientId` to your own in the example. The current client ID you have is the one I created for the example which of course doesn't have your domain whitelisted which is why you're getting the error. To fix please update the `clientId` to your own and rebuild (instructions in [example/ README.md](https://github.com/miguelmota/alexa-voice-service.js/tree/master/example))

Here's where you find the Client ID in the Alexa dashboard:

![security-profile](https://cloud.githubusercontent.com/assets/168240/26762573/742bf4c2-48f9-11e7-8528-0933e0e2fa73.jpg)
